### ISSUE TITLE
Cannot find IBSData after installling the package

### ISSUE THREAD

**Issue by carden24** [tapj/IBSMicrobiota#1]
Hi, 
I successfully installed the R package but I cannot load the data or find it in the repository. Do you have any suggestions?

> library(IBSMicrobiota)
> data(IBSData)
Warning message:
In data(IBSData) : data set ‘IBSData’ not found

**Comment by tapj** [comment]
Hi Erick,

Thank you for this request.

This repo was made only to show code not to share data publicly. I will check with the Principal Investigator how to share with you the full package with data included.

Julien

**Comment by carden24** [comment]
Thanks Julien

**Comment by carden24** [comment]
Do you have an update on the data availabilty?

**Comment by tapj** [comment]
Hi Erick,

I can not send you the data myself as I am not the clinical PI of this study.  I sent all formatted R data to the clinical PI Pr Magnus Simren. The best for you would be to contact him directly. You can find his email in the associated article published in Gastroenterology [http://dx.doi.org/10.1053/j.gastro.2016.09.049](http://dx.doi.org/10.1053/j.gastro.2016.09.049)

I will indicate this issue in the readme file of this repository.

Julien

**Comment by Nishida12** [comment]
Hi Julien,

I have same problem that I cannot load IBS data.
I sent an e-mail to Dr. Simren last week, but it may not be read.
Could you please help me to get the data?

Nishida

**Comment by tapj** [comment]
Hi Nishida,

I just asked Pr. Simren if he missed your email.
Sorry for the delay.


Julien
