### ISSUE TITLE
How to extract features

### ISSUE THREAD

**Issue by Nishida12** [tapj/IBSMicrobiota#2]
Hi Julien,

Your paper (https://www.gastrojournal.org/article/S0016-5085(16)35174-5/fulltext?referrer=https%3A%2F%2Fwww.ncbi.nlm.nih.gov%2F) explains how to extract features as follows.

"Model interpretation and marker extraction: features (bacterial OTUs) with potential association with IBS severity were extracted as nonzero coefficients from all 100 LASSO models (trained in 10 times resampled 10-fold cross-validation)."

But in your code of IBSMicrobiota_analysis.Rmd, features seemed to be extracted by 80% threshold as follows.
//
#select important species from the model (80% weight of the model)
selected.species = names(w[order(w[,5]),4][cumsum(w[order(w[,5]),5]) > (1-0.80)]) 
features.tax     = tax[selected.species,]
//

Do you have updated version?

Nishida

**Comment by tapj** [comment]
Hi Nishida,

Thank you for pointing this.

Yes you are right. The model extracted first the non zero features and to avoid any overfitting we added another filtering step selecting only those features representing 80% of cummulative weight of over each model training. This additional filtering step was not carefully reported in the manuscript.

so if you wanted to select all features, I would advise you to change this line

`selected.species = names(w[order(w[,5]),4][cumsum(w[order(w[,5]),5]) > (1-0.80)])`

to

`selected.species = names(w[order(w[,5]),4][cumsum(w[order(w[,5]),5]) > 0])`

I hope that help,

Julien

**Comment by Nishida12** [comment]
Hi Julien,

Thank you for your kind reply!
It clears my problem.

Nishida
